###

GET http://localhost:3000/user


###

GET http://localhost:3000/user?name=jhon



###

GET http://localhost:3000/user/12347

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "id": 1234;
  "email": "user1@gmail",
  "username": "user1",
  "password": "123456",
  "profilePicture": ""
}


###

PUT http://localhost:3000/user
Content-Type: application/json

{
    "_id": "12347",
    "name": "Moshe",
    "age": "22"
}


###

DELETE http://localhost:3000/user
Content-Type: application/json

{
    "_id": "12346",
    "name": "Moshe",
    "age": "22"
}


###

GET http://localhost:3000/post



###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "Elad",
    "email": "Elad@gmail.com",
    "password": "123456"
}




